version: "3"

services:
  api:
    build:
      dockerfile: "./docker/api/Dockerfile"
      context: "."
    env_file:
      - .env.local

  frontend:
    build:
      dockerfile: "./docker/frontend/Dockerfile"
      context: "."
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env.local
    volumes:
      - letsencrypt:/etc/letsencrypt


volumes:
  letsencrypt:
