version: "3"

services:
  api:
    build:
      dockerfile: "./docker/api/Dockerfile"
      context: "."

  frontend:
    build:
      dockerfile: "./docker/frontend/Dockerfile"
      context: "."
    environment:
      - API_HOST=api.no-karma.app
      - FRONTEND_HOST=no-karma.app
