version: "3"

services:
  api:
    build:
      dockerfile: "./docker/api/Dockerfile"
      context: "."
    env_file:
      - .env.local
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"

  frontend:
    build:
      dockerfile: "./docker/frontend/Dockerfile"
      context: "."
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env.local
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "5"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.certbotcron.schedule: "@midnight"
      ofelia.job-exec.certbotcron.command: "run-certbot.sh"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - frontend
    command: daemon --docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  letsencrypt:
