const fs = require("fs");
const Vuetify = require("vuetify");
const theme = {
  // See https://vuetifyjs.com/en/features/theme/
  options: {
    customProperties: true,
  },
  themes: {
    light: {
      red: "#e53935",
    },
    dark: {
      red: "#e53935",
    },
  },
};

function getTheme(dark, selector) {
  const styles = new Vuetify({
    theme: {
      ...theme,
      dark,
    },
  }).framework.theme.generatedStyles;
  return styles.replace(/^:root/, selector);
}

fs.writeFileSync(
  "src/styles/theme.scss",
  [
    "// WARNING! File autogenerated using scripts/generateTheme.js, do not modify manually",
    getTheme(false, ".v-application.theme--light"),
    getTheme(true, ".v-application.theme--dark"),
  ].join("\n\n") + "\n"
);
