name: E2E tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm audit --production
      - run: npm run test:e2e:headless -- -b ${{ matrix.browser }}